import { IsEmail, IsString, IsNotEmpty } from "class-validator";

export class UserLoginDto {
  @IsString()
  readonly username: string;

  @IsString()
  readonly password: string;

  // @IsString()
  // @IsNotEmpty()
  // readonly requestFrom: string;
}

// Generated by https://quicktype.io

export interface FBGetUserInfoResponse {
  id: string;
  name: string;
  email: string;
  picture: Picture;
}

export interface Picture {
  data: Data;
}

export interface Data {
  height: number;
  is_silhouette: boolean;
  url: string;
  width: number;
}

export interface GithubGetUserInfoResponse {
  avatar_url: string;
  id: number;
  login: string;
  name: string;
  email: string;
}
