import { ValidationError } from "class-validator";

export const enum StatusCodesList {
  ErrorOccured,
  Success,
  ValidationError,
  InternalServerError,
  NotFound,
  UnauthorizedAccess,
  TokenExpired,
  TooManyTries,
  ServiceUnAvailable,
  ThrottleError,
  Forbidden,
  IncorrectOldPassword,
  UserInactive,
  BadRequest,
  InvalidCredentials,
  InvalidRefreshToken,
  UnsupportedFileType,
  OtpRequired,
  DeleteDefaultError,
  RefreshTokenExpired,
  EmailOrPasswordIncorrect,
  EmailAlreadyExists,
  SettingNotFound,
  SettingAlreadyExists,
  Conflict,
  UserNotFound,
  TokenNotFound,
  DiscountNotFound,
  BlogNotFound,
  SeriesNotFound,
  TagNotFound,
}
